---
- name: Manage docker config & containers 
  hosts: all
  become: true
  gather_facts: false 

  tasks:  

# Docker

  - name: Docker started and enabled
    service:
      name: docker
      state: started
      enabled: true

# Vote
  - name: Vote container
    docker_container:
      name: vote
      image: docker.io/ekuchin/vote
      pull: true
      state: started
      ports: "2022:8080"
      restart_policy: unless-stopped

# Site

  - name: Site container
    docker_container:
      name: site
      image: docker.io/ekuchin/site:latest
      pull: true
      state: started
      ports: "80:8080"
      restart_policy: unless-stopped