---
- name: Configure Redhat
  hosts: all
  gather_facts: true

  vars:
    package_list:
      - mc
      - htop
      - podman
  
  tasks:
  - name: Install packages
    dnf:
      name: "{{item}}"
      state: present
    loop: "{{package_list}}"
    become: true