---
- name: Configure Redhat
  hosts: all
  gather_facts: false

  vars:
    package_list:
      - mc
      - htop
      - docker
  
  tasks:
  - name: Install packages
    dnf:
      name: "{{item}}"
      state: latest
    loop: "{{package_list}}"
    become: true